--- 
jobs: 
  inventoryjob: 
    docker: 
      - 
        image: "circleci/node:13.8.0"
    steps: 
      - checkout
      - 
        run: 
          command: |
              aws ec2 describe-instances \
                --query "Reservations[*].Instances[*].PublicIpAddress" \
                --output text >> .circleci/ansible/inventory.txt
          name: "Add back-end ip to ansible inventory"
version: 2.1
workflows: 
  welcome: 
    jobs: 
      - inventoryjob
