--- 
jobs: 
  inventoryjob: 
    docker: 
      - 
        image: amazon/aws-cli
    steps: 
      - checkout
      - 
        run:
        command: |
            aws configure \
              --Default region name [None]: us-west-2
      - 
        run: 
          command: |
              aws ec2 describe-instances \
                --query "Reservations[*].Instances[*].PublicIpAddress" \
                --output text >> .circleci/ansible/inventory.txt
          name: "Add back-end ip to ansible inventory"
      - 
        persist_to_workspace: 
          paths: 
            - project/.circleci/ansible/inventory.txt
          root: ~/
version: 2.1
workflows: 
  welcome: 
    jobs: 
      - inventoryjob
